export const templateVariables = [
  "{{orderId}}",
  "{{email}}",
  "{{nickname}}",
  "{{productName}}",
  "{{amount}}",
  "{{quantity}}",
  "{{totalAmount}}",
  "{{currency}}",
  "{{paidAt}}",
  "{{trackingNumber}}",
];

export const selectionTemplateVariables = [
  "{{selectionReference}}",
  "{{selectionLink}}",
  "{{selectionPageTitle}}",
  "{{customerName}}",
  "{{customerEmail}}",
  "{{customerContact}}",
  "{{supportEmail}}",
  "{{totalQuantity}}",
  "{{totalAmount}}",
  "{{currency}}",
  "{{items}}",
  "{{note}}",
  "{{submittedAt}}",
];

export const defaultBuyerEmailSubject = "Thank you for your purchase";

export const defaultBuyerEmailHtml = [
  '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;margin:0;padding:0;background-color:#ffffff;color:#352331;font-family:Avenir Next,Nunito,Trebuchet MS,Segoe UI,Arial,sans-serif;">',
  '<tbody><tr><td align="center" style="padding:18px 0px;">',
  '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:680px;margin:0 auto;border-collapse:separate;border-spacing:0;background-color:#fffdf5;border:1px solid #f3d5df;border-radius:22px;box-shadow:0 18px 48px rgba(152,36,79,0.12);">',
  '<tbody>',
  '<tr><td style="padding:24px 20px 20px;background-color:#ffe7f0;border-bottom:1px solid #f3d5df;border-radius:22px 22px 0px 0px;">',
  '<p style="margin:0px 0px 12px;color:#98244f;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Tiny booking treat</p>',
  '<h1 style="margin:0px 0px 10px;color:#352331;font-size:30px;line-height:1.16;font-weight:900;letter-spacing:0px;">Thank you, {{nickname}}</h1>',
  '<p style="margin:0;color:#776471;font-size:15px;line-height:1.65;">Your Misaki shop order is confirmed. We saved the details below for you.</p>',
  '</td></tr>',
  '<tr><td style="padding:18px 12px 8px;">',
  '<div style="background-color:#ffffff;border:1px solid #f3d5df;border-radius:20px;padding:18px;">',
  '<p style="margin:0px 0px 8px;color:#98244f;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Order complete</p>',
  '<p style="margin:0;color:#352331;font-size:17px;line-height:1.55;font-weight:800;word-break:break-word;">Order <span style="color:#98244f;">{{orderId}}</span> is complete.</p>',
  '<p style="margin:8px 0px 0px;color:#776471;font-size:14px;line-height:1.55;word-break:break-word;">{{productName}}</p>',
  '</div>',
  '</td></tr>',
  '<tr><td style="padding:4px 12px 8px;">',
  '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;border-collapse:separate;border-spacing:0px 8px;">',
  '<tbody>',
  '<tr><td style="padding:14px 18px;border-radius:16px;background-color:#ffffff;">',
  '<p style="margin:0px 0px 4px;color:#776471;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Product</p>',
  '<p style="margin:0;color:#352331;font-size:14px;font-weight:800;line-height:1.5;word-break:break-word;">{{productName}}</p>',
  '</td></tr>',
  '<tr><td style="padding:14px 18px;border-radius:16px;background-color:#ffffff;">',
  '<p style="margin:0px 0px 4px;color:#776471;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Quantity</p>',
  '<p style="margin:0;color:#352331;font-size:15px;font-weight:900;line-height:1.4;">{{quantity}}</p>',
  '</td></tr>',
  '<tr><td style="padding:18px 18px;border-radius:20px;background-color:#98244f;">',
  '<p style="margin:0px 0px 4px;color:#ffffff;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Total</p>',
  '<p style="margin:0;color:#ffffff;font-size:26px;font-weight:900;line-height:1.25;word-break:break-word;">{{currency}} {{totalAmount}}</p>',
  '</td></tr>',
  '<tr><td style="padding:14px 18px;border-radius:16px;background-color:#fff7fa;">',
  '<p style="margin:0px 0px 4px;color:#776471;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Paid at</p>',
  '<p style="margin:0;color:#352331;font-size:13px;font-weight:800;line-height:1.45;word-break:break-all;">{{paidAt}}</p>',
  '</td></tr>',
  '</tbody></table>',
  '</td></tr>',
  '<tr><td style="padding:8px 12px 18px;">',
  '<div style="background-color:#f3fff9;border:1px solid #c7f1e4;border-radius:20px;padding:18px;">',
  '<p style="margin:0px 0px 8px;color:#352331;font-size:16px;line-height:1.45;font-weight:900;">Need help with your order?</p>',
  '<p style="margin:0;color:#776471;font-size:14px;line-height:1.65;">If you have any questions, please contact <a href="mailto:diy@misaki.im" style="color:#cf2f6c;text-decoration:none;font-weight:900;">diy@misaki.im</a>.</p>',
  '</div>',
  '<p style="margin:14px 0px 0px;color:#776471;font-size:12px;line-height:1.5;text-align:center;"><span style="color:#98244f;font-weight:900;">Misaki Shop</span> · Secure PayPal checkout</p>',
  '</td></tr>',
  '</tbody>',
  '</table>',
  '</td></tr></tbody></table>',
].join("");

export const defaultAdminEmailSubject = "New order: {{orderId}}";

export const defaultAdminEmailHtml = [
  '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;margin:0;padding:0;background-color:#ffffff;color:#352331;font-family:Avenir Next,Nunito,Trebuchet MS,Segoe UI,Arial,sans-serif;">',
  '<tbody><tr><td align="center" style="padding:18px 0px;">',
  '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:680px;margin:0 auto;border-collapse:separate;border-spacing:0;background-color:#fffdf5;border:1px solid #f3d5df;border-radius:22px;box-shadow:0 18px 48px rgba(152,36,79,0.12);">',
  '<tbody>',
  '<tr><td style="padding:24px 20px 20px;background-color:#ffe7f0;border-bottom:1px solid #f3d5df;border-radius:22px 22px 0px 0px;">',
  '<p style="margin:0px 0px 12px;color:#98244f;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">New order</p>',
  '<h1 style="margin:0px 0px 10px;color:#352331;font-size:30px;line-height:1.16;font-weight:900;letter-spacing:0px;">Order {{orderId}}</h1>',
  '<p style="margin:0;color:#776471;font-size:15px;line-height:1.65;">A new Misaki Shop payment has been completed.</p>',
  '</td></tr>',
  '<tr><td style="padding:18px 12px 8px;">',
  '<div style="background-color:#ffffff;border:1px solid #f3d5df;border-radius:20px;padding:18px;">',
  '<p style="margin:0px 0px 8px;color:#98244f;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Buyer</p>',
  '<p style="margin:0;color:#352331;font-size:17px;line-height:1.55;font-weight:800;word-break:break-word;">{{email}}</p>',
  '<p style="margin:8px 0px 0px;color:#776471;font-size:14px;line-height:1.55;word-break:break-word;">Nickname: {{nickname}}</p>',
  '</div>',
  '</td></tr>',
  '<tr><td style="padding:4px 12px 8px;">',
  '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;border-collapse:separate;border-spacing:0px 8px;">',
  '<tbody>',
  '<tr><td style="padding:14px 18px;border-radius:16px;background-color:#ffffff;">',
  '<p style="margin:0px 0px 4px;color:#776471;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Product</p>',
  '<p style="margin:0;color:#352331;font-size:14px;font-weight:800;line-height:1.5;word-break:break-word;">{{productName}}</p>',
  '</td></tr>',
  '<tr><td style="padding:14px 18px;border-radius:16px;background-color:#ffffff;">',
  '<p style="margin:0px 0px 4px;color:#776471;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Quantity</p>',
  '<p style="margin:0;color:#352331;font-size:15px;font-weight:900;line-height:1.4;">{{quantity}}</p>',
  '</td></tr>',
  '<tr><td style="padding:18px 18px;border-radius:20px;background-color:#98244f;">',
  '<p style="margin:0px 0px 4px;color:#ffffff;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Total</p>',
  '<p style="margin:0;color:#ffffff;font-size:26px;font-weight:900;line-height:1.25;word-break:break-word;">{{currency}} {{totalAmount}}</p>',
  '</td></tr>',
  '<tr><td style="padding:14px 18px;border-radius:16px;background-color:#fff7fa;">',
  '<p style="margin:0px 0px 4px;color:#776471;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Paid at</p>',
  '<p style="margin:0;color:#352331;font-size:13px;font-weight:800;line-height:1.45;word-break:break-all;">{{paidAt}}</p>',
  '</td></tr>',
  '</tbody></table>',
  '</td></tr>',
  '<tr><td style="padding:8px 12px 18px;">',
  '<div style="background-color:#f3fff9;border:1px solid #c7f1e4;border-radius:20px;padding:18px;">',
  '<p style="margin:0px 0px 8px;color:#352331;font-size:16px;line-height:1.45;font-weight:900;">Next step</p>',
  '<p style="margin:0;color:#776471;font-size:14px;line-height:1.65;">Review the order in the admin panel and prepare fulfillment if needed.</p>',
  '</div>',
  '<p style="margin:14px 0px 0px;color:#776471;font-size:12px;line-height:1.5;text-align:center;"><span style="color:#98244f;font-weight:900;">Misaki Shop</span> · Seller notification</p>',
  '</td></tr>',
  '</tbody>',
  '</table>',
  '</td></tr></tbody></table>',
].join("");

export const defaultShipmentEmailSubject = "Your Misaki shop order has shipped: {{orderId}}";

export const defaultShipmentEmailHtml = [
  '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;margin:0;padding:0;background-color:#ffffff;color:#352331;font-family:Avenir Next,Nunito,Trebuchet MS,Segoe UI,Arial,sans-serif;">',
  '<tbody><tr><td align="center" style="padding:18px 0px;">',
  '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:680px;margin:0 auto;border-collapse:separate;border-spacing:0;background-color:#fffdf5;border:1px solid #f3d5df;border-radius:22px;box-shadow:0 18px 48px rgba(152,36,79,0.12);">',
  '<tbody>',
  '<tr><td style="padding:24px 20px 20px;background-color:#ffe7f0;border-bottom:1px solid #f3d5df;border-radius:22px 22px 0px 0px;">',
  '<p style="margin:0px 0px 12px;color:#98244f;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Shipment update</p>',
  '<h1 style="margin:0px 0px 10px;color:#352331;font-size:30px;line-height:1.16;font-weight:900;letter-spacing:0px;">Your order shipped</h1>',
  '<p style="margin:0;color:#776471;font-size:15px;line-height:1.65;">Hi {{nickname}}, your Misaki Shop order is on the way.</p>',
  '</td></tr>',
  '<tr><td style="padding:18px 12px 8px;">',
  '<div style="background-color:#ffffff;border:1px solid #f3d5df;border-radius:20px;padding:18px;">',
  '<p style="margin:0px 0px 8px;color:#98244f;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Tracking number</p>',
  '<p style="margin:0;color:#352331;font-size:22px;line-height:1.35;font-weight:900;word-break:break-all;"><a href="https://t.17track.net/en#nums={{trackingNumber}}" target="_blank" rel="noopener noreferrer" style="color:#98244f;text-decoration:none;font-weight:900;">{{trackingNumber}}</a></p>',
  '<p style="margin:8px 0px 0px;color:#98244f;font-size:13px;line-height:1.55;font-weight:800;word-break:break-word;">Click the tracking number to view delivery details.</p>',
  '<p style="margin:8px 0px 0px;color:#776471;font-size:14px;line-height:1.55;word-break:break-word;">Order {{orderId}}</p>',
  '</div>',
  '</td></tr>',
  '<tr><td style="padding:4px 12px 8px;">',
  '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;border-collapse:separate;border-spacing:0px 8px;">',
  '<tbody>',
  '<tr><td style="padding:14px 18px;border-radius:16px;background-color:#ffffff;">',
  '<p style="margin:0px 0px 4px;color:#776471;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Product</p>',
  '<p style="margin:0;color:#352331;font-size:14px;font-weight:800;line-height:1.5;word-break:break-word;">{{productName}}</p>',
  '</td></tr>',
  '<tr><td style="padding:14px 18px;border-radius:16px;background-color:#ffffff;">',
  '<p style="margin:0px 0px 4px;color:#776471;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Quantity</p>',
  '<p style="margin:0;color:#352331;font-size:15px;font-weight:900;line-height:1.4;">{{quantity}}</p>',
  '</td></tr>',
  '<tr><td style="padding:18px 18px;border-radius:20px;background-color:#98244f;">',
  '<p style="margin:0px 0px 4px;color:#ffffff;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Total</p>',
  '<p style="margin:0;color:#ffffff;font-size:26px;font-weight:900;line-height:1.25;word-break:break-word;">{{currency}} {{totalAmount}}</p>',
  '</td></tr>',
  '<tr><td style="padding:14px 18px;border-radius:16px;background-color:#fff7fa;">',
  '<p style="margin:0px 0px 4px;color:#776471;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Paid at</p>',
  '<p style="margin:0;color:#352331;font-size:13px;font-weight:800;line-height:1.45;word-break:break-all;">{{paidAt}}</p>',
  '</td></tr>',
  '</tbody></table>',
  '</td></tr>',
  '<tr><td style="padding:8px 12px 18px;">',
  '<div style="background-color:#f3fff9;border:1px solid #c7f1e4;border-radius:20px;padding:18px;">',
  '<p style="margin:0px 0px 8px;color:#352331;font-size:16px;line-height:1.45;font-weight:900;">Thank you for supporting Misaki Shop</p>',
  '<p style="margin:0;color:#776471;font-size:14px;line-height:1.65;">If you have any questions, please contact <a href="mailto:diy@misaki.im" style="color:#cf2f6c;text-decoration:none;font-weight:900;">diy@misaki.im</a>.</p>',
  '</div>',
  '<p style="margin:14px 0px 0px;color:#776471;font-size:12px;line-height:1.5;text-align:center;"><span style="color:#98244f;font-weight:900;">Misaki Shop</span> · Shipment notification</p>',
  '</td></tr>',
  '</tbody>',
  '</table>',
  '</td></tr></tbody></table>',
].join("");

export const defaultSelectionEmailSubject = "Your selection has been received: {{selectionReference}}";

export const defaultSelectionEmailHtml = [
  '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;margin:0;padding:0;background-color:#ffffff;color:#352331;font-family:Avenir Next,Nunito,Trebuchet MS,Segoe UI,Arial,sans-serif;">',
  '<tbody><tr><td align="center" style="padding:18px 0px;">',
  '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:680px;margin:0 auto;border-collapse:separate;border-spacing:0;background-color:#fffdf5;border:1px solid #f3d5df;border-radius:22px;box-shadow:0 18px 48px rgba(152,36,79,0.12);">',
  '<tbody>',
  '<tr><td style="padding:24px 20px 20px;background-color:#dcfcf1;border-bottom:1px solid #c7f1e4;border-radius:22px 22px 0px 0px;">',
  '<p style="margin:0px 0px 12px;color:#0f766e;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Selection received</p>',
  '<h1 style="margin:0px 0px 10px;color:#352331;font-size:30px;line-height:1.16;font-weight:900;letter-spacing:0px;">Thank you, {{customerName}}</h1>',
  '<p style="margin:0;color:#5f5360;font-size:15px;line-height:1.65;">We saved your picks from {{selectionPageTitle}}. You can review them anytime with the link below.</p>',
  '</td></tr>',
  '<tr><td style="padding:18px 12px 8px;">',
  '<div style="background-color:#ffffff;border:1px solid #f3d5df;border-radius:20px;padding:18px;">',
  '<p style="margin:0px 0px 8px;color:#98244f;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Reference</p>',
  '<p style="margin:0;color:#352331;font-size:20px;line-height:1.45;font-weight:900;word-break:break-word;">{{selectionReference}}</p>',
  '<p style="margin:8px 0px 0px;color:#776471;font-size:14px;line-height:1.55;word-break:break-all;"><a href="{{selectionLink}}" style="color:#cf2f6c;text-decoration:none;font-weight:900;">View your selection</a></p>',
  '</div>',
  '</td></tr>',
  '<tr><td style="padding:4px 12px 8px;">',
  '<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;border-collapse:separate;border-spacing:0px 8px;">',
  '<tbody>',
  '<tr><td style="padding:14px 18px;border-radius:16px;background-color:#ffffff;">',
  '<p style="margin:0px 0px 4px;color:#776471;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Items</p>',
  '<div style="color:#352331;font-size:14px;font-weight:800;line-height:1.65;word-break:break-word;">{{items}}</div>',
  '</td></tr>',
  '<tr><td style="padding:14px 18px;border-radius:16px;background-color:#fff7fa;">',
  '<p style="margin:0px 0px 4px;color:#776471;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Quantity</p>',
  '<p style="margin:0;color:#352331;font-size:16px;font-weight:900;line-height:1.4;">{{totalQuantity}}</p>',
  '</td></tr>',
  '<tr><td style="padding:18px 18px;border-radius:20px;background-color:#98244f;">',
  '<p style="margin:0px 0px 4px;color:#ffffff;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Total</p>',
  '<p style="margin:0;color:#ffffff;font-size:26px;font-weight:900;line-height:1.25;word-break:break-word;">{{totalAmount}}</p>',
  '</td></tr>',
  '<tr><td style="padding:14px 18px;border-radius:16px;background-color:#ffffff;">',
  '<p style="margin:0px 0px 4px;color:#776471;font-size:12px;font-weight:900;line-height:1.3;text-transform:uppercase;">Submitted at</p>',
  '<p style="margin:0;color:#352331;font-size:13px;font-weight:800;line-height:1.45;word-break:break-all;">{{submittedAt}}</p>',
  '</td></tr>',
  '</tbody></table>',
  '</td></tr>',
  '<tr><td style="padding:8px 12px 18px;">',
  '<div style="background-color:#f3fff9;border:1px solid #c7f1e4;border-radius:20px;padding:18px;">',
  '<p style="margin:0px 0px 8px;color:#352331;font-size:16px;line-height:1.45;font-weight:900;">Need to update something?</p>',
  '<p style="margin:0;color:#776471;font-size:14px;line-height:1.65;">Open your selection link or reply to this email. Contact: <a href="mailto:{{supportEmail}}" style="color:#cf2f6c;text-decoration:none;font-weight:900;">{{supportEmail}}</a></p>',
  '<p style="margin:8px 0px 0px;color:#776471;font-size:14px;line-height:1.55;word-break:break-all;"><a href="{{selectionLink}}" style="color:#cf2f6c;text-decoration:none;font-weight:900;">View your selection</a></p>',
  '</div>',
  '<p style="margin:14px 0px 0px;color:#776471;font-size:12px;line-height:1.5;text-align:center;"><span style="color:#98244f;font-weight:900;">Misaki Shop</span> · Selection confirmation</p>',
  '</td></tr>',
  '</tbody>',
  '</table>',
  '</td></tr></tbody></table>',
].join("");
